name: lighthouse

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            https://toyotacarrental.com.ph/
          uploadArtifacts: true # Save results as an action artifact
          temporaryPublicStorage: true # Upload report to temporary public storage
